# Generated by Django 5.2.7 on 2025-10-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FakEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('identity', models.CharField(max_length=200, unique=True)),
                ('payment_status', models.CharField(max_length=100)),
                ('whatsapp_name', models.CharField(blank=True, max_length=200, null=True)),
                ('entry_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
