# Generated by Django 5.2.7 on 2025-10-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('residency_number', models.CharField(max_length=200, unique=True)),
                ('company', models.CharField(max_length=200)),
                ('expiry_date', models.DateField()),
            ],
        ),
    ]
